// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5boX0M41jLKSaikkrAGuWzVR6HkmUyKI',
    appId: '1:527112916114:web:85c7e8c8eee08b4ec42a4b',
    messagingSenderId: '527112916114',
    projectId: 'nearme-ebdb8',
    authDomain: 'nearme-ebdb8.firebaseapp.com',
    storageBucket: 'nearme-ebdb8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Vs1V69UL9ZNQDrE1sg9k4DC-YCdkkYw',
    appId: '1:527112916114:android:c9a2848583367d3ac42a4b',
    messagingSenderId: '527112916114',
    projectId: 'nearme-ebdb8',
    storageBucket: 'nearme-ebdb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvM646fofHYgawiCY_5o_FrhTINaDmJYg',
    appId: '1:527112916114:ios:751cea93800eac6bc42a4b',
    messagingSenderId: '527112916114',
    projectId: 'nearme-ebdb8',
    storageBucket: 'nearme-ebdb8.firebasestorage.app',
    iosBundleId: 'com.example.nearMe',
  );
}
